### ISSUE TITLE
Update Quiz to Angular 5.x

### ISSUE THREAD

**Issue by sqlsolver** [softgandhi/ng2-quiz#1]
This is being submitted as a suggestion for an enhancement to this already excellent quiz app. These are the steps I took to use it in an Angular-cli 1.6.2 app running on Angular 5.1.2 (as a component, rather than a standalone app).

- Created the Quiz component with ng g component [name] and copied this project's HTML code verbatim.  
- Copied the Models and Services folders as siblings of the App folder, and the Data folder one level higher.  
- Moved the CSS at the root of this project into my new component's CSS file.  
- Modified the project's .angular-cli.json file to serve the .json test files from the assets folder in the distribution as shown [here](https://github.com/angular/angular-cli/wiki/stories-asset-configuration#project-assets), and then modified ./services/quiz.server.ts paths inside the getAll function:  
````
getAll() {
    return [
      { id: 'assets/aspnet.json', name: 'Asp.Net' },
      { id: 'assets/csharp.json', name: 'C Sharp' },
      { id: 'assets/designPatterns.json', name: 'Design Patterns' }
    ];
  }
````  
- After updating to the new HttpClient @angular/common/http properties of text and json were no longer available on the retrieved object in quiz.service.ts get method and it was shortened to:  
````
get(url){
  return this.http.get(url).map(res => <Response>res);
}
````  
- Routed to the quiz component as to any other, and of course imported and declared it in the app module.

**Comment by softgandhi** [comment]
Thanks. I will update the app to angular 5.x soon.

**Comment by macliems** [comment]
Thanks. A really good starter project for quiz apps! Looking forward to your angular 5 update.

**Comment by softgandhi** [comment]
Apology, could not get time for it. Will update to angular 5 this weekend. Will also update it with more features eventually.

**Comment by macliems** [comment]
Great! Are you working on a feature for quizzes with more than 1 kind of
question,  e.g. multiple choice, true/false, answer input, fill in blanks ?
Later this year I'll need to create such a quiz, so .....

Kind regards, Mac

2018-02-08 10:03 GMT+01:00 Anurag Gandhi <notifications@github.com>:

**Comment by softgandhi** [comment]
yes, its there in my to do list. but i can't assure on when i will do it.
For details: [https://www.codeproject.com/Articles/1167451/Quiz-Application-in-Angular](https://www.codeproject.com/Articles/1167451/Quiz-Application-in-Angular)

**Comment by softgandhi** [comment]
This app is updated to angular 5 version. 
Thank you.
